### ISSUE TITLE
Delete mandate gives 204 exception

### ISSUE THREAD

**Issue by esprange** [mollie/mollie-api-php#193]
if the revokeMandate method of customers is used, an exception is raised because of an empty body return. I used Postman to similate this and it returns indeed a 204 status. The work-around is a catching this exception, but in fact it should not be an exception at all...

**Comment by willemstuursma** [comment]
Hi @esprange. Is this in the v1 or v2 version of this client?

**Comment by esprange** [comment]
I am using v2.

**Comment by esprange** [comment]
And Willem, I found the issue while in testmode. But I don't think that should matter.

**Comment by Smitsel** [comment]
Hi @esprange,

We've added a check for the 204 response code to the parsing of the body.
So we won't throw an exception when the body is empty and the code is 204.

So you will now get an empty response. Since this is in line with the empty response from the api.
So you can use a try catch around the revoke, when it succeeds you can be sure that it is deleted.
