### ISSUE TITLE
How to send mail to customer after payment is paid using webhook

### ISSUE THREAD

**Issue by flowroma** [mollie/mollie-api-php#200]
I have a checkout form where the customer fills in their data (name, address, etc) and on submit, the action refers to mollie payment.

`<form method="post" action="ideal/examples/01-new-payment.php" class="data-validate">  
input name, address, phone etc.
<button class="btn btn-primary btn-lg" value="submit"><span>Betaal met iDeal</span></button>`

All goes well, I am refered to the external page and in test mode I set the payment to paid. Now the webhook is called. The webhook uses $_POST to get the name, address, phone of the customer filled out during checkout and e-mails that to the customer. See attached webhook script. 
![deel1](https://user-images.githubusercontent.com/40252194/41385261-b3500596-6f7a-11e8-96f6-5bcdc716b9df.PNG)
![deel2](https://user-images.githubusercontent.com/40252194/41385262-b36c6fd8-6f7a-11e8-88b8-36a9ce6629e1.PNG)
Customer is subsequently  redirected to the confirmation page, see relevant script excerpt:

![deel3](https://user-images.githubusercontent.com/40252194/41385387-8b4964ba-6f7b-11e8-8a60-043151828bc9.PNG)

Now the 2 problems are:
1. No mail is being sent whatsoever. What is wrong in my logic?
2. The confirmation page always outputs the else statement.

**Comment by Smitsel** [comment]
Hi @flowroma,

Your problem should probably be resolved by debugging.
Make sure you have error reporting on while testing this script.

1. Try to var_dump the $mailSent right after calling $mail->send(). So you know if the sending of mail was successful. 

2. Try to var_dump the $status, it's going into your else because its not "paid". So try to find out with var_dump what it is exactly. The order might have not been found or the status has not been properly updated in the database.

So the main tip, try to verify if your variables contain what you expect using var_dump.

Hope it helps!

**Comment by flowroma** [comment]
Dear @Smitsel 
Thanks for your reply. I added the error_reporting and the following code in the webhook file

```
if (!$mailsent)
    {
         echo "Mailer Error: " . $mail->ErrorInfo;

    }
    else
    {
            header("location:http://grandcafeleyaal.nl/foutmelding");
    }

?>
```

But it doesn't give any errors or redirect me to the error page. Regarding point 2, the status is updated in the database as 'paid', yet the confirmation page shows the else statement "Er is iets niet goed gegaan met de betaling". I don't get any errors.

I haven't tried the var_dump yet, and will try and update with the results.

**Comment by flowroma** [comment]
I solved the issue by putting the post parameters from the checkout form in sessions. The issue now is that the webhook file gives me the following errors;

Notice: Undefined index: id in /public_html/ideal/examples/02-webhook-verification.php on line 16
API call failed: Invalid payment ID: ''. A payment ID should start with 'tr_'.

Line 16: `$payment = $mollie->payments->get($_POST["id"]);`

I read the developer portal on retrieving the payment ID, but I can't figure out what this is and how it differs from orderID. Anyway, How do I solve this problem? I already hardcoded some values starting with tr_ in the code, and still no success :/

**Comment by Smitsel** [comment]
When u create a payment, mollie will call the webhook specified in webhookUrl when creating a payment. We will then POST the id of the payment to your script. 

The error u are mentioning is because this $_POST["id"] is empty. You should either test this with hardcoding. Or create a test payment and host your webhook so it can be reached and see if it works.

On https://docs.mollie.com/index we have some guides how this works.

**Comment by flowroma** [comment]
Thanks! issue resolved using live key

**Comment by toonvandeputte** [comment]
I can heartily recommend using Postman to test responses from the Mollie API (and the response from your own webhook). Postman is an API development platform, but they have a great (and free) desktop app with lots of handy features to test API responses: https://www.getpostman.com/apps

**Comment by Smitsel** [comment]
Thanks, great suggestion @toonvandeputte.

This issue seems to be resolved now.
