### ISSUE TITLE
status: canceled or cancelled? webhook in test mode

### ISSUE THREAD

**Issue by boban-dj** [mollie/mollie-api-php#211]
## Specifications

  - API Version: V2

## Describe the issue

When the webhook is being called, my status gets updated fine. Only when the status is canceled, I get the status: cancelled (2 L's). In the API docs this was corrected. Also when calling payments API directly it shows : canceled. (which is according the docs [ https://docs.mollie.com/guides/payment-status-changes#every-possible-payment-status)]( https://docs.mollie.com/guides/payment-status-changes#every-possible-payment-status))
I think the test payment API is not updated yet?

**Comment by Smitsel** [comment]
Hi, i've been looking into your issue but i can't see to find out what the problem is.

When creating a payment and using the webhook script from the examples. The payment gets retrieved from Mollie. The status for ``v2`` calls gives me ``canceled``.

So please elaborate more on your issue with some code examples. Because ``v2`` calls always come back with ``canceled`` instead of our old ``v1`` status with double ll.

**Comment by boban-dj** [comment]
So `$status = $payment->status; ` returns `Your payment status is 'cancelled'.` 
I have just a simple update function in the webhook:
`function updateStatusMolly ($status, $method, $order_id) {
	$worker = new MysqlWrapper(Database::get('members'));
	$update = array( 'status' => $status, 'method' => $method );
	$update_where = array( 'order_id' => $order_id );
	$worker->update( 'transactions', $update, $update_where, 1 );
}`
then
`
$payment  = $mollie->payments->get($_POST["id"]);
	$order_id = $payment->metadata->order_id;

	$status = $payment->status;
	$method = $payment->method;
	
if ($payment->isPaid() == TRUE) {
		//At this point you'd probably want to start the process of delivering the product to the customer.
updateStatusMolly($status,$method,$order_id);`

In my db ist saved as "cancelled"
I hope i cleared it more with some code, here a screenshot with the result
![screenshot_2018-06-27_10-58-38](https://user-images.githubusercontent.com/5364226/41963975-29ce97ea-79f9-11e8-8dc5-2b1d913c2250.png)

**Comment by Smitsel** [comment]
What strikes me as odd is that when using the code above, you retrieve the payment:
``$mollie->payments->get($_POST["id"]);``
And then use that as ``$status`` for storing the order.

So if you var_dump the ``$payment->status`` will this show ``canceled`` or ``cancelled``?

**Comment by boban-dj** [comment]
Where you suggest to do the var_dump? from the webhook nothing can be dumped. so the only way is to catch it in a db or text file. 
Why dont you try to `grep --include=* -rinw . -e "cancelled"`
I am sure it comes from Molly?

**Comment by boban-dj** [comment]
Its saving cancelled here in the webhook
```php
} elseif ($payment->isPaid() == FALSE) {
	
	//~ echo "<pre>";
	//~ echo var_dump($status);
	//~ echo "</pre>";
	//~ die;
		updateStatusMolly($status,$method,$order_id);	

	}
```
but its just returns "open" when actually canceled. 
When trying to add more logic (as in the Molly php examples) I had some problems thats why I leave it just with `$payment->isPaid()`

**Comment by Smitsel** [comment]
Hi @boban-dj,

`cancelled` is still present in the v1 api.
The v2 api uses the new `canceled`.

So this needs to be debugged as it's probably something like the v1 being called.
Or the wrong value gets saved. Because v2 calls do not come back with `cancelled`.

You can debug and var_dump this when using something like ngrok.
