### ISSUE TITLE
Prevent payment id to expire?

### ISSUE THREAD

**Issue by haayman** [mollie/mollie-api-php#262]
## Specifications

  - API Version: PHP 1.8

## Describe the issue

I'm writing a ticket-reservation system with the ability to cancel the tickets and get a refund.
In my dev environment I sometimes get an error 'invalid payment id'. It appears that the payments expire? Can this be prevented? If not: what's the expiration period? Is it the same for dev/production?

**Comment by toonvandeputte** [comment]
Are you using the test mode? Because payments in test mode disappear after a set amount of time. This is normal behaviour, but poorly document. I've had the same kind of thing happened and it took me a while to figure out what was going on.

In live mode and for normal expired payments, the API will not return 'invalid payment id', but will rather return the payment with a status of 'expired'.

AFAIK it is not possible to create payments that do not expire. Bank transfers have the longest expiration time, at 15 days.

**Comment by haayman** [comment]
Ouch, that destroys the entire idea behind my site. Thanks (I don't mean
that sarcastically :-))

Op ma 3 sep. 2018 23:45 schreef Toon Van de Putte <notifications@github.com

**Comment by ndijkstra** [comment]
Hi, test mode payments are not being deleted anymore: https://docs.mollie.com/changelog/v2/changelog#tuesday-31st

For bank transfer payments, you can set a maximum of 100 days. [See due date in our docs](https://docs.mollie.com/reference/v2/payments-api/create-payment#bank-transfer).

For our other payment expiry times you can read our [status changes guide](https://docs.mollie.com/payments/status-changes#expiry-times-per-payment-method).
