### ISSUE TITLE
Settlement::payments() doesn't work

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-php#280]
## Specifications

  - API Version: v2

## Describe the issue

> Bij de migratie van API v1 naar v2 loop ik tegen een issue bij de settlements aan. Het opvragen van settlements en de details daarvan (via de PHP library) gaat prima, maar als ik van een settlement vervolgens de (bijvoorbeeld) betalingen wil opvragen krijg ik een exceptie "You have not set an API key or OAuth access token. Please use setApiKey() to set the API key.". Dat is gek, want de settlement zelf wordt wel met die token opgehaald. Het lijkt alsof de geauthoriseerde client niet opnieuw voor de andere resources gebruikt wordt?
> 
> Dus bijvoorbeeld:
> 
> ```php
> $mollie = new \Mollie\Api\MollieApiClient();
> $mollie->setApiKey(...);
> $mollie->setAccessToken(...);
> 
> $settlement = $mollie->settlements->get($settlementId);
> ```
>
> Bovenstaande gaat goed. Maar als ik vervolgens verder graaf:
> 
> ```php
> $settlement->payments();
> ``` 
>
> Krijg ik bovenstaande exceptie voor m'n neus.

**Comment by willemstuursma** [comment]
@sandervanhooft any clues?

**Comment by sandervanhooft** [comment]
So at this point I'd need to look at the specific customer's implementation code to find out what's going on exactly.

**Comment by SanderVanLeeuwen** [comment]
That would be me. And I have a confession to make 😅

Triggered by your remark that this works fine in your tests, I made simpler test which works fine here too. The issue seems to be related to some caching on our side. We are migrating from API v1 to v2, and in v1 it was no problem to cache the API results. But in the v2 setup it seems to be an issue.

It still feels like a bug though, as I'd still like to cache the results to limit the amount of external requests. For example, using apcu, the following throws an Exception:

```php
$settlement = $mollie->settlements->get('stl_x');

// This works
var_dump($settlement->payments());

apcu_add('test', $settlement, 300);
$cachedSettlement = apcu_fetch('test');

// Now it's broken
var_dump($cachedSettlement->payments());
```
Any thoughts on why the initialised client doesn't properly persist in the cached result?

**Comment by willemstuursma** [comment]
The client is stored in the objects (so that future calls can be done straight from the object). This prevents serialization.

**Comment by sandervanhooft** [comment]
@willemstuursma Would a `setClient(MollieApiClient $client)` method on the BaseResource be helpful here?

**Comment by SanderVanLeeuwen** [comment]
It's not a very big deal, but such a method would be helpful to somewhat reduce the number of duplicate calls.
