### ISSUE TITLE
Cannot see the settlements in API v1

### ISSUE THREAD

**Issue by robindirksen1** [mollie/mollie-api-php#330]
## Specifications

  - API Version: v1

## Describe the issue

I cannot request the settlements via API v1 but I can do it via API v2. How is it possible that the organization access tokens are not valid on both API versions?

Request (via CURL & PHP)
```
curl -X GET https://api.mollie.com/v1/settlements \
>     -H "Authorization: Bearer access_xxxxxx"
```

Response:
```
{"error":{"type":"request","message":"Unauthorized request","links":{"documentation":"https://docs.mollie.com/"}}}
```

**Comment by MollieRick** [comment]
Hi @robindirksen1,
Thanks for your message. I think that the Organization Access Tokens are added to the v1-documentation by mistake. 

We do not support these keys in the v1 because that version is deprecated, therefor we do not add new functionality to it like the Organizations Access Tokens. 

I will create an issue at our [documentation repo](https://github.com/mollie/api-documentation).

**Comment by robindirksen1** [comment]
Hi @MollieRick, thanks for the explanation and I will upgrade to the v2 api to use the settlements API. 

Link to issue on documentation repo: https://github.com/mollie/api-documentation/issues/346
