### ISSUE TITLE
Can not include pricing

### ISSUE THREAD

**Issue by mro95** [mollie/mollie-api-php#375]
## Specifications

  - API Version: 2

## Describe the issue

Im trying to get a list of methods with prices. When I was trying to include the prices from the active methods, everything works fine.

```
$mollieMethods = $mollie->methods->allActive(['include' => 'pricing']);
````

But when i try to include the prices of all (available) methods i get an error
```
$mollieMethods = $mollie->methods->allAvailable(['include' => 'pricing']);
```

The error:
```
Error executing API call (422: Unprocessable Entity): Non-existent body parameter "include" for this API call.. Field: include. Documentation: https://docs.mollie.com/guides/handling-errors
```

I was trying to find the problem and noticed that in `MethodEndpoint.php:63` the `allAvailable` method inserts the parameters as JSON body, and the `allActive` method creates a query string. That might be the problem.

**Comment by sandervanhooft** [comment]
thanks @mro95 for this detailed report. I'm looking into it.

**Comment by sandervanhooft** [comment]
The issue is indeed that there's query params ("filters") are being treated as body ("data") in this case.

We'll need to support both, so I'm going to split these into two parameters here.

```php
public function allAvailable(array $data = [], array $filters = []);
```

**Comment by sandervanhooft** [comment]
I'll need to go over the other method endpoint methods as well :).

**Comment by sandervanhooft** [comment]
@MollieRick 

Need some input here. We have three ways to deal with this. My preference goes to one, as long as we can the impact is not to severe.

**1**
If we follow this client's convention the parameter order should be: `$data, $filter`.

But adopting that in the other MethodEndpoint methods will cause a BC. Since these are quite new features, we're probably ok, but I can't really guess the impact from here.

**2**
Adopting the order `$filter, $data` in these cases would not be a BC, but breaks with our own convention. On the long term, this is not the right choice imho.

**3**
Another way would be to stick to one single parameter, and filter out the ones that should be passed as query string instead (`include`, `profileId`). The downside here is that it's harder to maintain.

Which way should we go?

**Comment by MollieRick** [comment]
Thanks @sandervanhooft for the detailed purposal. I can not make this decision at my own. we'll need to discuss this with @willemstuursma as well.

**Comment by sandervanhooft** [comment]
@MollieRick I understand. I have drafted a PR #377 .

**Comment by willemstuursma** [comment]
We need two types of parameters for allMethods? It is a GET request, so there should only be query string parameters right?

It doesn't make sense to add a `$data` parameter to this shorthand, inside the shorthand the parameters should be mapped to the right locations in the "deeper" methods.

**Comment by sandervanhooft** [comment]
Thanks @willemstuursma for clearing this up.

Ok, this is easier than I thought it would be. Since all MethodEndpoint requests are `GET`, there's only the query string parameter to take into account. So I have reverted to a single parameter.

I agree that a mapping is a more dev/user-friendly way than using two parameters (in case modifying requests like `POST`), will use that whenever I come across the use case (not here).

**Comment by sandervanhooft** [comment]
I've released a patch just now. If you run `composer update` or `composer update mollie/mollie-api-php` it should update to the `v2.8.3` php core client.

[Release info here](https://github.com/mollie/mollie-api-php/releases/tag/v2.8.3)

**Comment by Bekcomp** [comment]
I was searching and first came across this post, and then found the following information.
Since April 28, 2025, include=pricing has been removed from the Methods API.
https://docs.mollie.com/changelog/pricing-information-removed-from-methods-api-endpoints
