### ISSUE TITLE
Webhook is only called in case of status paid (test mode)

### ISSUE THREAD

**Issue by webprogrammierer** [mollie/mollie-api-php#510]
## Specifications

  - API Version: v2

## Describe the issue

I am using the example code (/mollie-api-php/examples/payments) 
- create-payment.php
- return.php
- webhook.php

It works fine and I can select one of 2 payment methods. After selecting one of them I can select the status and then click on continue.

If I selected "Paid" everything is okay, the webhook is called and the browser is redirected to payments/return.php?order_id=..

But if I selected one of the other options (open, failed, canceled, expired) the webhook is NOT called and the browser is not redirected to return.php, instead redirected to mollie.com/payscreen/select-method/xxx . 

**That's why any code of any of the status except paid cannot be tested!**

Please provide a method to test the php code for all status states and call the webhook.php in all cases.
Thank you very much.

**Comment by MollieRick** [comment]
Hi @webprogrammierer,

Thanks for your message. By reading "It works fine and I can select one of 2 payment methods", I assume that you not set an explicit method for your test payment. If a payment fails due to any reason, the consumer get the opportunity to select a new method to try again, so the webhook will not be called then. This situation is the same in live mode.

You need to set the `method` if you want to test the webhook for `failed`, `canceled` and `expired`, Please note that we never send a webhook call for `open`.

Let me know if this helps!

Cheers,
Rick

**Comment by webprogrammierer** [comment]
Yes, I understand this.

But there is still an error:
When method is not set programmatically, then at first I can select the method. Maybe I select "creditcard". After that I can set the status for creditcard payment with the radio buttons. Still if I select "failed" or one of the other options except "paid", no webhook is called BUT (and this is the error), the return.php is called anyway.

If return.php gets called always the webhook should be called too.

**Comment by MollieRick** [comment]
Can you provide me a payment ID (`tr_xxx`) of one of the payments where this happened?

**Comment by sandervanhooft** [comment]
If I understand correctly, the return.php is tied to the redirectUrl, not the webhookUrl.

**Comment by EricKarijo** [comment]
> If I understand correctly, the return.php is tied to the redirectUrl, not the webhookUrl.

Yes, this is true.
In the beginning I was also confused about this.

**Comment by sandervanhooft** [comment]
So after completing the checkout (also in test mode), the customer is always returned to the `redirectUrl`.

In this case this means that `return.php` always gets executed. So it's not a bug.

Note that the `webhookUrl` does not get called on all status changes (see the docs [here](https://docs.mollie.com/guides/webhooks#endpoints-supporting-webhooks) and [here](https://docs.mollie.com/payments/status-changes)). This is by design.

**Comment by sandervanhooft** [comment]
Does this answer your question @EricKarijo ?

**Comment by webprogrammierer** [comment]
It is not a great problem, maybe you can ignore it.

But my problem was:
When using testmode AND more (!) then one paying method is activated, only in this case:
I can select with the mollie select widged.
After selection (e.g. I selected creditcard, but there are others to select), THEN I will test "open, failed, canceled, expired", but this is not possible to test, because mollie DOES NOT return (with webhook and return.php) but always a NEW selection is necessary!!! The only way to return is to select "paid" after selecting one of the paying methods that are activated (there must be at least 2).

Only in this case the problem occurs and in this case the php code for open, failed, canceled and expired CAN NOT be tested, because mollie does not return, it always want a new method to be selected from the mollie widget.

Workaround is, only use one (!) method in php script, then open, failed, canceled, expired returns to script (webhook.php and return.php), only in this case it works and die PHP code for this states can be tested.
