### ISSUE TITLE
API v1: creditcard temporarily not available

### ISSUE THREAD

**Issue by JorritDiepstraten** [mollie/mollie-api-php#566]
## Specifications

  - API Version: 1.19.13

## Describe the issue

After starting a creditcard transaction, the following error appears:
**Error executing API call (system): Payment platform for this payment method temporarily not available.**

We use method "creditcard", which was working for years. The other payment methods work perfectly. We haven't changed anything in the website. Mollie support can't help us unfortunately.

**Comment by sandervanhooft** [comment]
Thanks for reporting.

This seems to be an issue reported by the API, not an issue with this package.

Nevertheless I'll ping Mollie to see if they know anything about a creditcard outage.

**Comment by JorritDiepstraten** [comment]
This issue started last weekend or earlier. We don't receive any creditcard payments since then.

**Comment by dabroek** [comment]
@JorritDiepstraten We have identified and solved the issue you reported. The issue occurred because we introduced a new (stricter) validation policy in one of our subsystems. Unfortunately, due to a very specific set of circumstances, only a small subset of merchants was impacted which is why it went unnoticed until now. We apologize for the inconvenience caused and will make sure this issue cannot reoccur.
