### ISSUE TITLE
Add support for HTTP proxies

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-php#63]
There is no way to set HTTP proxies now.

**Comment by Ricknox** [comment]
Hi Willem 👋 

There are some problems I'd like to resolve before I contribute (I'd like to contribute to this issue since this affects me too); Are you expecting to use the native cURL proxy method? If so, there are various options regarding authentication. See the [documentation](http://php.net/manual/en/function.curl-setopt.php) that has some (version problems) and are you trying to support all various ways of authentication?

Let me know how you'd see this solution.

Thanks,
Ricardo.

**Comment by willemstuursma** [comment]
I guess we should have a connection string similar to [Guzzle Options](http://docs.guzzlephp.org/en/latest/request-options.html) for setting the proxy. The `Mollie_Api_Client` will then set the right properties on the cURL resource. 

/cc @mollierobbert

**Comment by Ricknox** [comment]
Let me know what your opinion is @mollierobbert. Thanks! 👍

**Comment by willemstuursma** [comment]
@mollierobbert is pretty busy today. If it works for Guzzle, it'll work for us too, so go ahead.

**Comment by willemstuursma** [comment]
@Ricknox any luck with this?

**Comment by holtkamp** [comment]
Similar issue and PR can be found here: https://github.com/link0/bunq/issues/27

**Comment by willemstuursma** [comment]
@holtkamp That's a pretty unique requirement of bunq. 

Regardless, I _think_ we will release a v2 of this API client somewhere in 2018H1, which will probably use a Guzzle `ClientInterface` that you can optionally inject.

**Comment by willemstuursma** [comment]
This will be available in 2.0, which uses Guzzle as the transport. Guzzle can be configured to use proxies and can be injected in the constructor.
