### ISSUE TITLE
Which API endpoint do we have to use to make a payment from mollie to IBAN

### ISSUE THREAD

**Issue by newmediacrew** [mollie/mollie-api-php#691]
## Specifications

  - API Version: 2.59

## Describe the issue
We can make payments from customer to Mollie (https://docs.mollie.com/reference/v2/payments-api/create-payment) . Which API endpoint do we need to use for making a payment from Mollie to a specific IBAN bank account? 
...

**Comment by robindirksen1** [comment]
The payout is handled using the settlement API, it's only possible to payout to your own (verified business) IBAN account.

**Comment by sandervanhooft** [comment]
Hi @newmediacrew ,

As Robin states it is not possible to wire funds directly to third party bank accounts.

If you need to wire funds to your company's account, you can manage that in the [Mollie Dashboard](https://my.mollie.com/dashboard).

In case you're looking for marketplace features (i.e. split inbound payments and route these to other connected Mollie accounts), you can read more here: [Mollie Connect for Marketplaces](https://www.mollie.com/products/connect/marketplaces).

I hope this helps, feel free to reach out here otherwise.
