### ISSUE TITLE
Recurring / subscription payment methods clarification

### ISSUE THREAD

**Issue by DePalmo** [mollie/mollie-api-php#79]
The documentations on your website are not quite clear on this one, so I'm posting a question here.

From your documentation I figured out that these are the correct steps to create a subscription (please correct me if wrong):
1. check if customer already exist in Mollie database and if not, create it
2. use customer ID returned by API to create first payment with `recurringType=first` for that customer
3. redirect customer to URL returned by API where they can select payment method (more about this below)
4. when customer returns to (our) website, check if any `Mandate` is active or pending for that customer and create a subscription, where same payment method is used as customer selected in step 3
5. if all goes well, subscription is created

A few issues or better to say, questions regarding steps above:
1. Payment method. Why customer can't select `SEPA Direct Debit` on first payment?
2. How a customer can use a SEPA Direct Debit for subscription? Please provide exact steps to take.
3. In my test environment, I only enabled SEPA Direct Debit, but I got listed other payment methods as well (please note that all methods except SEPA Direct Debit were disabled). Why?
4. Do payment method iDeal, SOFORT, MisterCash, Bitcoin, KBC, Belfius support recurring billing? If not, why are they listed when customer is making first payment? What happens when customer selects any of payment methods that does not support recurring billing and a recurring billing was created and next period for billing happens?

**Comment by ndijkstra** [comment]
Recurring payments are only possible with the payment methods SEPA Direct Debit and Creditcard.
For the first payment you can use iDEAL, Bancontact, SOFORT, Belfius and KBC (recurring with SEPA Direct Debit) & Creditcard (recurring with Creditcard).

It's not possible to use SEPA Direct Debit as one-time payment method or first payment. When a customer finish a first payment with for example iDEAL, the subscription payment is automatically a SEPA Direct Debit payment. If the customer uses a creditcard as first payment the subscription payment is a Creditcard payment.

**Comment by DePalmo** [comment]
Thank you for a clarification!

**Comment by mikey242** [comment]
Sorry to hijack this old issue. @ndijkstra your response was very helpful here as I am trying to further understand how subscriptions work with SEPA Direct Debit.

My question is about payment methods used for the 'first' payment. When you submit a payment request with the sequence type 'first' and don't specify the payment methods, Mollie will automatically present the user with a list of payment methods that can be used as a first payment. However, if SEPA Direct Debit is disabled on the account, iDEAL is still shown (since it is valid as a first payment method) but the subscription will not be set up since SEPA Direct Debit is disabled.

Am I correct in assuming that in this scenario it is up to me to determine which payment methods are available depending on the status of SEPA Direct Debit and pass that as a parameter when creating the payment?

**Comment by ndijkstra** [comment]
Hi @mikey242 

If SEPA Direct Debit is not active, ideal and other SEPA methods are not shown as first payment method

**Comment by mikey242** [comment]
Thanks for letting me know @ndijkstra!
